apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "secrext.name" . }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ .Values.externalSecret.target.name | default (printf "%s-ecr" (include "secrext.name" .) | quote) }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{`{{ .proxy_endpoint }}`}}": {
                "username": "{{`{{ .username }}`}}",
                "password": "{{`{{ .password }}`}}"
              }
            }
          }
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: {{ printf "%s-ecr-auth" (include "secrext.name" .) | quote }}