apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrext.name" . }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.secret.aws_access_key_id | b64enc|  quote }}
  aws_secret_access_key: {{ .Values.secret.aws_secret_access_key | b64enc | quote }}