name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags

jobs:
  release:
    runs-on: gha-minikube-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.17.3'

      - name: Package Helm chart
        run: helm package .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: '*.tgz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}